import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { build } from 'esbuild';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outputDir = path.join(rootDir, 'dist');
const outputPath = path.join(outputDir, '[Chat] Template Text Folders.user.js');
const legacyOutputPath = path.join(rootDir, '[Chat] Template Text Folders.user.js');
const legacyConfigOutputDir = path.join(outputDir, 'config');
const legacyDriveOutputPath = path.join(outputDir, '[Chat] Template Text Folders.drive-sync.js');

const userscriptHeaderPath = path.join(rootDir, 'src', 'userscript', 'header.js');
const userscriptNotesPath = path.join(rootDir, 'src', 'userscript', 'notes.md');
const entryPath = path.join(rootDir, 'src', 'main.js');
const officialUserStylePath = path.join(rootDir, 'userstyle', '[Chat] Template Text Folders.user.css');
const generatedOfficialStyleBundlePath = path.join(rootDir, 'src', 'features', 'domain-style', 'official-style-bundle.generated.js');

const OFFICIAL_STYLE_SOURCE_URL = 'https://github.com/0-V-linuxdo/Chat_Template_Text_Folders/raw/dev/userstyle/%5BChat%5D%20Template%20Text%20Folders.user.css';

const NOTE_BANNER_WIDTH = 70;

function createBannerLine(label) {
    const text = ` ${label.trim()} `;
    if (text.length >= NOTE_BANNER_WIDTH) {
        return text.trim();
    }
    const padTotal = NOTE_BANNER_WIDTH - text.length;
    const left = Math.floor(padTotal / 2);
    const right = padTotal - left;
    return `${'='.repeat(left)}${text}${'='.repeat(right)}`;
}

function stripMarkdownFormatting(text) {
    return text
        .replace(/\*\*(.*?)\*\*/g, '$1')
        .replace(/`([^`]+)`/g, '`$1`');
}

function convertMarkdownLine(line) {
    const trimmed = line.trim();
    if (!trimmed) {
        return '';
    }
    if (/^---+$/.test(trimmed)) {
        return '-'.repeat(Math.min(NOTE_BANNER_WIDTH, 74));
    }
    const headingMatch = /^##\s*(.+)$/.exec(trimmed);
    if (headingMatch) {
        return stripMarkdownFormatting(headingMatch[1]);
    }
    const listMatch = /^-\s+(.*)$/.exec(trimmed);
    if (listMatch) {
        return `   • ${stripMarkdownFormatting(listMatch[1])}`;
    }
    return stripMarkdownFormatting(trimmed);
}

function renderNoteMarkdownAsComment(markdownSource) {
    const normalized = markdownSource.replace(/\r\n/g, '\n').trim();
    if (!normalized) {
        return '/* NOTE: empty note content */';
    }

    const rawLines = normalized.split('\n').map((line) => line.trimEnd());
    if (rawLines.length < 2) {
        return `/* ${stripMarkdownFormatting(rawLines[0] || 'NOTE')} */`;
    }

    const startLabel = stripMarkdownFormatting(rawLines[0].replace(/^#\s*/, '').trim() || 'IMPORTANT · NOTICE · START');
    const endLabel = stripMarkdownFormatting(rawLines[rawLines.length - 1].replace(/^#\s*/, '').trim() || 'IMPORTANT · NOTICE · END');
    const bodyLines = rawLines.slice(1, -1);

    const lines = [];
    lines.push(`/* ${createBannerLine(startLabel)}`);
    for (const bodyLine of bodyLines) {
        const converted = convertMarkdownLine(bodyLine);
        if (converted === '') {
            lines.push(' *');
        } else {
            lines.push(` * ${converted}`);
        }
    }
    lines.push(` * ${createBannerLine(endLabel)}`);
    lines.push(' */');

    return lines.join('\n');
}

function ensureOutputDir() {
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }
}

async function generateOfficialStyleBundleArtifact() {
    if (!fs.existsSync(officialUserStylePath)) {
        throw new Error(`Official userstyle missing: ${officialUserStylePath}`);
    }

    const formatModulePath = path.join(rootDir, 'src', 'features', 'domain-style', 'style-format.js');
    const formatModule = await import(pathToFileURL(formatModulePath).href);
    if (!formatModule || typeof formatModule.buildOfficialStyleBundleFromUserCss !== 'function') {
        throw new Error('Official style parser module is invalid.');
    }

    const sourceText = fs.readFileSync(officialUserStylePath, 'utf8');
    const bundle = formatModule.buildOfficialStyleBundleFromUserCss(sourceText, {
        sourceUrl: OFFICIAL_STYLE_SOURCE_URL,
        lastFetchedAt: 0,
    });

    const artifactSource = [
        '/* This file is auto-generated by scripts/build.mjs. Do not edit manually. */',
        '',
        `const OFFICIAL_STYLE_SOURCE_URL = ${JSON.stringify(OFFICIAL_STYLE_SOURCE_URL)};`,
        '',
        `const OFFICIAL_STYLE_BUNDLE = ${JSON.stringify(bundle, null, 4)};`,
        '',
        'export { OFFICIAL_STYLE_BUNDLE, OFFICIAL_STYLE_SOURCE_URL };',
        '',
    ].join('\n');

    fs.mkdirSync(path.dirname(generatedOfficialStyleBundlePath), { recursive: true });
    fs.writeFileSync(generatedOfficialStyleBundlePath, artifactSource, 'utf8');
    console.log(`ℹ️ Generated official style bundle: ${path.relative(rootDir, generatedOfficialStyleBundlePath)}`);
}

function removeLegacyArtifacts() {
    const removablePaths = [
        legacyOutputPath,
        legacyDriveOutputPath,
        legacyConfigOutputDir,
    ];

    removablePaths.forEach((targetPath) => {
        if (!fs.existsSync(targetPath)) {
            return;
        }
        const stat = fs.statSync(targetPath);
        if (stat.isDirectory()) {
            fs.rmSync(targetPath, { recursive: true, force: true });
        } else {
            fs.rmSync(targetPath, { force: true });
        }
        console.log(`ℹ️ Removed legacy artifact: ${path.relative(rootDir, targetPath)}`);
    });
}

async function runBuild() {
    if (!fs.existsSync(userscriptHeaderPath)) {
        throw new Error(`Userscript header missing: ${userscriptHeaderPath}`);
    }
    if (!fs.existsSync(userscriptNotesPath)) {
        throw new Error(`Userscript notes missing: ${userscriptNotesPath}`);
    }
    if (!fs.existsSync(entryPath)) {
        throw new Error(`Entry file missing: ${entryPath}`);
    }

    await generateOfficialStyleBundleArtifact();
    ensureOutputDir();

    const headerSource = fs.readFileSync(userscriptHeaderPath, 'utf8').trim();
    const noteSource = fs.readFileSync(userscriptNotesPath, 'utf8');
    const banner = `${headerSource}\n\n${renderNoteMarkdownAsComment(noteSource)}\n`;

    await build({
        entryPoints: [entryPath],
        outfile: outputPath,
        bundle: true,
        format: 'iife',
        platform: 'browser',
        target: 'es2020',
        banner: {
            js: banner,
        },
        legalComments: 'none',
        charset: 'utf8',
        logLevel: 'info',
    });

    removeLegacyArtifacts();
    console.log(`✅ Build complete: ${path.relative(rootDir, outputPath)}`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
    try {
        await runBuild();
    } catch (error) {
        console.error('❌ Build failed:', error instanceof Error ? error.message : String(error));
        process.exitCode = 1;
    }
}

export { runBuild };
